### ISSUE TITLE
Clarify responsibility of library

### ISSUE THREAD

**Issue by oskarth** [status-im/status-nim#1]
Right now it's a bit confusing since this library mostly contains (sloppy) Go code. Clarify what the lines are between Nimbus, this library, and e.g. status-console-client (or any other client).

Similar to status-go, it'd be useful to have a library that wraps a node (geth/Nimbus). This includes more Status specific stuff, can be consumed by clients, such as status-console-client.

---

A follow up issue of this is to provide a better API for consumers. E.g. instead of hardcoded behavior in https://github.com/status-im/status-nim/blob/master/main.go this should be an actual API, similar to what status-go provides to status-console-client

**Comment by oskarth** [comment]
Also see https://github.com/status-im/nimbus/pull/360 for relevant discussion

**Comment by oskarth** [comment]
@PombeirP given the new code architecture, do you have a preference for what to do with this issue (and library)?

**Comment by PombeirP** [comment]
I think this repo can be deleted, I don't foresee it being used.

**Comment by oskarth** [comment]
Sounds good
